    - name: Add more info to thread
      vars:
        slack_domain: electronic-arts.slack.com
        # slack_channel: "#template_patching"
      community.general.slack:
        channel: "{{ slack_channel }}"
        token: "{{slack_api_token}}"
        thread_id: "{{slackthreadid}}"
        # thread_id: "{{ slacknotification['ts'] }}"
        color: "{{colorcode}}"
        msg: "{{slackmsg}}"
      delegate_to: localhost
